export class CommonConstants {
  // 全屏宽度
  public static readonly FULL_WIDTH = '100%';
  // 全屏高度
  public static readonly FULL_HEIGHT = '100%';
}

export enum RouterMap {
  // 订座页面
  BOOK_PAGE = 'BookPage',
  // 订座订单页面
  BOOK_ORDER_PAGE = 'BookOrderPage',
  // 订座结果页面
  BOOK_RES_PAGE = 'BookResPage',
  // 排号页面
  QUEUE_PAGE = 'QueuePage',
  // 排号订单页面
  QUEUE_ORDER_PAGE = 'QueueOrderPage',
  // 排号结果页面
  QUEUE_RES_PAGE = 'QueueResPage',
  // 订单管理页面
  ORDER_LIST_PAGE = 'OrderPage',
}

